apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: eclipse-temurin:17-jdk-alpine
      command: ["java", "-jar", "/app/app.jar"]
      volumeMounts:
        - name: app-volume
          mountPath: /app
  volumes:
    - name: app-volume
      hostPath:
        path: /tmp/deploy
        type: DirectoryOrCreate
