apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: eclipse-temurin:17-jdk-alpine
      # Așteaptă până apare /app/app.jar, apoi pornește aplicația
      command: ["sh","-c","while [ ! -f /app/app.jar ]; do echo '⌛ waiting for /app/app.jar'; sleep 2; done; exec java -jar /app/app.jar"]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
